// apps/web/src/components/admin/BinFormatter.tsx
import { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '../../api/client';
import { Copy, CheckCircle, Database, FileText, ArrowRight } from 'lucide-react';

export default function BinFormatter() {
  const [mode, setMode] = useState<'db' | 'manual'>('db');
  const [manualInput, setManualInput] = useState('');
  const [startIndex, setStartIndex] = useState(1);
  const [batchSize, setBatchSize] = useState(10);
  const [copied, setCopied] = useState(false);

  // Fetch clients from DB
  const { data, isLoading, error } = useQuery({
    queryKey: ['all-clients-bins'],
    queryFn: async () => {
      const res = await (apiClient as any).api.clients.$get({
        query: { limit: '5000' } // Fetch a large number to ensure we get all BINs
      });
      const json = await res.json();
      return json.data || [];
    },
    enabled: mode === 'db'
  });

  // Extract all BINs based on selected mode
  const allBins = useMemo(() => {
    if (mode === 'db') {
      if (!data) return [];
      return data.map((client: any) => client.bin).filter(Boolean);
    } else {
      // Split manual input by newlines, commas, or semicolons
      return manualInput
        .split(/[\n,;]+/)
        .map(b => b.trim())
        .filter(b => b.length > 0);
    }
  }, [mode, data, manualInput]);

  // Compute the final formatted string
  const formattedOutput = useMemo(() => {
    if (allBins.length === 0) return '';
    // Arrays are 0-indexed, but user input is 1-indexed
    const start = Math.max(0, startIndex - 1);
    const end = start + batchSize;
    const selectedBins = allBins.slice(start, end);
    return selectedBins.join(';');
  }, [allBins, startIndex, batchSize]);

  const handleCopy = () => {
    if (!formattedOutput) return;
    navigator.clipboard.writeText(formattedOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto p-4 md:p-8 space-y-6">
      <div className="bg-slate-800/50 p-6 rounded-2xl border border-slate-700">
        <h2 className="text-2xl font-bold text-slate-100 mb-2">BIN Formatter</h2>
        <p className="text-slate-400">Extract and format BIN numbers easily for copying.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left Column: Input Settings */}
        <div className="bg-slate-800 p-6 rounded-2xl border border-slate-700 space-y-6">
          
          {/* Mode Selector */}
          <div className="flex bg-slate-900 rounded-xl p-1">
            <button
              onClick={() => setMode('db')}
              className={`flex-1 flex items-center justify-center space-x-2 py-2.5 rounded-lg text-sm font-medium transition-all ${
                mode === 'db' ? 'bg-blue-600 text-white shadow-md' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Database size={16} />
              <span>Database</span>
            </button>
            <button
              onClick={() => setMode('manual')}
              className={`flex-1 flex items-center justify-center space-x-2 py-2.5 rounded-lg text-sm font-medium transition-all ${
                mode === 'manual' ? 'bg-blue-600 text-white shadow-md' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileText size={16} />
              <span>Manual Paste</span>
            </button>
          </div>

          {/* Mode specific content */}
          {mode === 'db' ? (
            <div className="p-4 bg-blue-900/20 border border-blue-500/20 rounded-xl">
              <h3 className="text-slate-200 font-medium mb-1">Database Mode</h3>
              {isLoading ? (
                <p className="text-blue-400 text-sm animate-pulse">Loading clients...</p>
              ) : error ? (
                <p className="text-red-400 text-sm">Failed to load clients.</p>
              ) : (
                <p className="text-slate-400 text-sm">
                  Successfully loaded <span className="text-blue-400 font-bold">{allBins.length}</span> BINs from the database.
                </p>
              )}
            </div>
          ) : (
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">Paste BINs here</label>
              <textarea
                value={manualInput}
                onChange={(e) => setManualInput(e.target.value)}
                placeholder="Enter BINs separated by newline, comma, or semicolon..."
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-slate-200 focus:outline-none focus:border-blue-500 min-h-[120px]"
              />
              <p className="text-xs text-slate-500 mt-2">
                Found {allBins.length} valid BINs from input.
              </p>
            </div>
          )}

          {/* Range Selector */}
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-4">Select Range (1-indexed)</label>
            <div className="flex items-center space-x-4">
              <div className="flex-1">
                <span className="text-xs text-slate-500 block mb-1">Start No.</span>
                <input
                  type="number"
                  min={1}
                  value={startIndex}
                  onChange={(e) => setStartIndex(parseInt(e.target.value) || 1)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-2.5 text-slate-200 focus:outline-none focus:border-blue-500 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                />
              </div>
              <ArrowRight className="text-slate-600 mt-5" />
              <div className="flex-1">
                <span className="text-xs text-slate-500 block mb-1">Batch Size</span>
                <input
                  type="number"
                  min={1}
                  value={batchSize}
                  onChange={(e) => setBatchSize(parseInt(e.target.value) || 1)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-2.5 text-slate-200 focus:outline-none focus:border-blue-500 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                />
              </div>
            </div>
            <p className="text-xs text-slate-500 mt-2">
              Will generate BINs from index {startIndex} to {startIndex + batchSize - 1}
            </p>
          </div>
        </div>

        {/* Right Column: Output */}
        <div className="bg-slate-800 p-6 rounded-2xl border border-slate-700 flex flex-col">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-semibold text-slate-200">Formatted Output</h3>
            <span className="text-xs font-medium bg-slate-900 text-slate-400 px-3 py-1 rounded-full border border-slate-700">
              {formattedOutput ? formattedOutput.split(';').length : 0} Items Selected
            </span>
          </div>
          
          <div className="flex-1 bg-slate-900 rounded-xl border border-slate-700 p-4 relative overflow-hidden group">
            <textarea
              readOnly
              value={formattedOutput}
              placeholder="Output will appear here..."
              className="w-full h-full min-h-[200px] bg-transparent text-slate-300 focus:outline-none resize-none font-mono text-sm"
            />
            
            {formattedOutput && (
              <div className="absolute bottom-4 right-4">
                <button
                  onClick={handleCopy}
                  className={`flex items-center space-x-2 px-4 py-2 rounded-lg font-medium transition-all shadow-lg ${
                    copied 
                      ? 'bg-emerald-500 text-white shadow-emerald-500/25' 
                      : 'bg-blue-600 hover:bg-blue-500 text-white shadow-blue-500/25'
                  }`}
                >
                  {copied ? <CheckCircle size={18} /> : <Copy size={18} />}
                  <span>{copied ? 'Copied!' : 'Copy'}</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// src/resources/src/pages/admin/BinFormatter.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from "vue";
import axios from "axios";

interface ClientRecord {
  id: number;
  name: string;
  bin: string;
  clientType: string;
  isActive: boolean;
}

const mode = ref<"db" | "manual">("db");
const manualInput = ref("");
const statusFilter = ref<"all" | "active" | "inactive">("active");
const selectedClientType = ref<string>("all");
const startIndex = ref<number>(1);
const batchSize = ref<number>(10);
const copied = ref(false);
const isLoading = ref(false);

// Clean raw BIN into numeric string
const cleanBin = (raw: string): string => {
  if (!raw) return "";
  return raw.replace(/\D/g, "");
};

// Format raw BIN into standard NBR xxxxxxxxx-xxxx format
const formatBin = (raw: string): string => {
  if (!raw) return "";
  const digits = raw.replace(/\D/g, "");
  if (digits.length >= 13) {
    return `${digits.slice(0, 9)}-${digits.slice(9, 13)}`;
  }
  if (digits.length > 9) {
    return `${digits.slice(0, 9)}-${digits.slice(9)}`;
  }
  return digits;
};

// Client Master Dataset from Database
const clients = ref<ClientRecord[]>([]);

// Dynamic Client Types
const clientTypesList = computed(() => {
  const set = new Set<string>();
  clients.value.forEach((c) => {
    if (c.clientType) set.add(c.clientType);
  });
  return Array.from(set);
});

// Fetch Clients from API
const fetchDbClients = async () => {
  isLoading.value = true;
  try {
    const res = await axios.get("/api/clients?limit=5000");
    if (res.data?.data && Array.isArray(res.data.data)) {
      clients.value = res.data.data.map((c: any) => ({
        id: c.id,
        name: c.companyName || c.name || "Unnamed Client",
        bin: c.binNumber || c.bin || "",
        clientType: c.customerTypeName || c.clientTypeName || c.clientType || "Standard",
        isActive: c.isActive !== false
      }));
    }
  } catch (err) {
    console.error("Failed to load clients for BIN formatter:", err);
  } finally {
    isLoading.value = false;
  }
};

onMounted(() => {
  fetchDbClients();
});

// Filtered DB Clients
const filteredDbClients = computed(() => {
  let list = clients.value;
  if (statusFilter.value === "active") {
    list = list.filter((c) => c.isActive === true);
  } else if (statusFilter.value === "inactive") {
    list = list.filter((c) => c.isActive === false);
  }
  if (selectedClientType.value !== "all") {
    list = list.filter((c) => c.clientType === selectedClientType.value);
  }
  return list;
});

// Available BINs list
const allAvailableBins = computed<string[]>(() => {
  if (mode.value === "db") {
    return filteredDbClients.value
      .filter((c) => c.bin && cleanBin(c.bin).length >= 9)
      .map((c) => formatBin(c.bin));
  } else {
    return manualInput.value
      .split(/[\r\n,;]+/)
      .map((t) => formatBin(t.trim()))
      .filter((t) => cleanBin(t).length >= 9);
  }
});

const totalBinsCount = computed(() => allAvailableBins.value.length);

// Sliced Batch based on Range
const selectedBatchBins = computed(() => {
  const total = allAvailableBins.value.length;
  if (total === 0) return [];
  const start = Math.max(0, (startIndex.value || 1) - 1);
  const size = Math.max(1, batchSize.value || 10);
  return allAvailableBins.value.slice(start, start + size);
});

// Semicolon Formatted Output String
const formattedOutput = computed(() => {
  if (selectedBatchBins.value.length === 0) return "";
  return selectedBatchBins.value.join(";");
});

// Range bounds
const rangeEnd = computed(() => {
  const total = allAvailableBins.value.length;
  if (total === 0) return 0;
  const start = Math.max(1, startIndex.value || 1);
  const size = Math.max(1, batchSize.value || 10);
  return Math.min(start + size - 1, total);
});

// Batch Navigation
const prevBatch = () => {
  const size = Math.max(1, batchSize.value || 10);
  const currentStart = Math.max(1, startIndex.value || 1);
  startIndex.value = Math.max(1, currentStart - size);
};

const nextBatch = () => {
  const size = Math.max(1, batchSize.value || 10);
  const currentStart = Math.max(1, startIndex.value || 1);
  const total = allAvailableBins.value.length;
  if (currentStart + size <= total) {
    startIndex.value = currentStart + size;
  }
};

const setQuickPreset = (start: number, size: number) => {
  startIndex.value = start;
  batchSize.value = size;
};

// Reset on mode/filter changes
watch([mode, statusFilter, selectedClientType], () => {
  startIndex.value = 1;
});

// Copy Handler
const copyToClipboard = async () => {
  if (!formattedOutput.value) return;
  try {
    await navigator.clipboard.writeText(formattedOutput.value);
    copied.value = true;
    setTimeout(() => {
      copied.value = false;
    }, 2000);
  } catch (err) {
    console.error("Failed to copy", err);
  }
};

const clearManualInput = () => {
  manualInput.value = "";
  startIndex.value = 1;
};
</script>

<template>
  <div class="bin-formatter-page">
    <!-- Header with Stats -->
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-4">
      <div>
        <div class="d-flex align-items-center gap-2 mb-1">
          <router-link to="/" class="text-muted text-decoration-none small">
            <i class="bi bi-arrow-left me-1"></i> Dashboard
          </router-link>
          <span class="text-muted small">/</span>
          <span class="text-primary small fw-semibold">BIN Formatter</span>
        </div>
        <h4 class="text-white fw-bold mb-0">BIN Batch Extractor & Formatter</h4>
        <span class="text-muted small">
          Extract, filter, and batch client BIN numbers separated by semicolons for NBR VAT portal lookups
        </span>
      </div>

      <!-- Quick KPI Chips -->
      <div class="d-flex align-items-center gap-2 mt-3 mt-md-0">
        <div class="kpi-chip">
          <span class="kpi-label">Available BINs</span>
          <span class="kpi-val text-info">{{ totalBinsCount }}</span>
        </div>
        <div class="kpi-chip">
          <span class="kpi-label">Batch Size</span>
          <span class="kpi-val text-success">{{ selectedBatchBins.length }}</span>
        </div>
        <div class="kpi-chip d-none d-sm-flex">
          <span class="kpi-label">Delimiter</span>
          <span class="kpi-val text-warning">Semicolon (;)</span>
        </div>
      </div>
    </div>

    <!-- Main Two-Column Layout -->
    <div class="row g-4">
      <!-- LEFT COLUMN: Mode Switcher, Database Filters, and Range Controls -->
      <div class="col-lg-6">
        <div class="card-panel h-100 d-flex flex-column">
          <!-- 1. Source Mode Switcher -->
          <div class="mode-switcher-wrap mb-3">
            <button
              type="button"
              class="mode-switch-btn"
              :class="{ active: mode === 'db' }"
              @click="mode = 'db'"
            >
              <i class="bi bi-database-fill me-2"></i> Database Mode
            </button>
            <button
              type="button"
              class="mode-switch-btn"
              :class="{ active: mode === 'manual' }"
              @click="mode = 'manual'"
            >
              <i class="bi bi-clipboard-data me-2"></i> Manual Paste Mode
            </button>
          </div>

          <!-- 2A. DATABASE EXTRACTION FILTERS -->
          <div v-if="mode === 'db'" class="db-filter-panel mb-3 p-3 rounded-3">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <span class="text-white fw-semibold small d-flex align-items-center gap-2">
                <i class="bi bi-funnel-fill text-primary"></i> Database Filters
              </span>
              <span v-if="isLoading" class="spinner-border spinner-border-sm text-primary"></span>
              <span v-else class="badge bg-dark border border-secondary text-info font-monospace" style="font-size: 0.75rem;">
                {{ totalBinsCount }} / {{ clients.length }} Clients
              </span>
            </div>

            <div class="row g-2">
              <!-- Filter 1: Status Filter -->
              <div class="col-sm-6">
                <label class="form-label text-muted small mb-1">1. Business Status</label>
                <select v-model="statusFilter" class="form-select form-select-sm idp-input">
                  <option value="all">All Statuses</option>
                  <option value="active">Active Clients Only</option>
                  <option value="inactive">Inactive Clients Only</option>
                </select>
              </div>

              <!-- Filter 2: Customer Type Filter -->
              <div class="col-sm-6">
                <label class="form-label text-muted small mb-1">2. Customer Type</label>
                <select v-model="selectedClientType" class="form-select form-select-sm idp-input">
                  <option value="all">All Types ({{ clientTypesList.length }})</option>
                  <option v-for="t in clientTypesList" :key="t" :value="t">
                    {{ t }}
                  </option>
                </select>
              </div>
            </div>
          </div>

          <!-- 2B. MANUAL PASTE AREA -->
          <div v-else class="manual-paste-panel mb-3">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <label class="form-label text-white small fw-medium mb-0">
                Paste BINs (Newline, comma, or semicolon separated)
              </label>
              <button
                type="button"
                class="btn btn-link btn-sm p-0 text-muted small text-decoration-none"
                @click="clearManualInput"
              >
                <i class="bi bi-trash me-1"></i> Clear
              </button>
            </div>
            <textarea
              v-model="manualInput"
              class="form-control idp-input font-monospace"
              rows="4"
              placeholder="e.g.&#10;001234567-0101&#10;002345678-0202, 003456789-0303&#10;004567890-0404; 005678901-0505"
            ></textarea>
            <div class="d-flex justify-content-between align-items-center text-muted small mt-1">
              <span>Detected valid BINs: <strong class="text-info">{{ totalBinsCount }}</strong></span>
            </div>
          </div>

          <!-- 3. RANGE & BATCH ENGINE -->
          <div class="range-panel p-3 rounded-3 flex-grow-1 d-flex flex-column justify-content-between">
            <div>
              <div class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-white fw-semibold small d-flex align-items-center gap-2">
                  <i class="bi bi-sliders text-info"></i> Range & Batch Selection
                </span>
                <span class="text-muted small">1-Indexed Position</span>
              </div>

              <div class="row g-3 mb-3">
                <!-- Start Index -->
                <div class="col-6">
                  <label class="form-label text-muted small mb-1">Start No. (Item #)</label>
                  <div class="input-group input-group-sm">
                    <button
                      class="btn btn-dark border-secondary"
                      type="button"
                      :disabled="startIndex <= 1"
                      @click="startIndex = Math.max(1, startIndex - 1)"
                    >
                      <i class="bi bi-dash"></i>
                    </button>
                    <input
                      v-model.number="startIndex"
                      type="number"
                      min="1"
                      :max="totalBinsCount || 1"
                      class="form-control idp-input text-center fw-bold font-monospace"
                    />
                    <button
                      class="btn btn-dark border-secondary"
                      type="button"
                      :disabled="startIndex >= totalBinsCount"
                      @click="startIndex = Math.min(totalBinsCount, startIndex + 1)"
                    >
                      <i class="bi bi-plus"></i>
                    </button>
                  </div>
                </div>

                <!-- Batch Size -->
                <div class="col-6">
                  <label class="form-label text-muted small mb-1">Batch Size (Count)</label>
                  <div class="input-group input-group-sm">
                    <button
                      class="btn btn-dark border-secondary"
                      type="button"
                      :disabled="batchSize <= 1"
                      @click="batchSize = Math.max(1, batchSize - 1)"
                    >
                      <i class="bi bi-dash"></i>
                    </button>
                    <input
                      v-model.number="batchSize"
                      type="number"
                      min="1"
                      max="100"
                      class="form-control idp-input text-center fw-bold font-monospace"
                    />
                    <button
                      class="btn btn-dark border-secondary"
                      type="button"
                      @click="batchSize = batchSize + 1"
                    >
                      <i class="bi bi-plus"></i>
                    </button>
                  </div>
                </div>
              </div>

              <!-- Fast Navigation & Quick Presets -->
              <div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-3">
                <div class="btn-group" role="group">
                  <button
                    type="button"
                    class="btn btn-dark border-secondary btn-sm"
                    :disabled="startIndex <= 1"
                    @click="prevBatch"
                  >
                    <i class="bi bi-chevron-left me-1"></i> Prev Batch
                  </button>
                  <button
                    type="button"
                    class="btn btn-dark border-secondary btn-sm"
                    :disabled="startIndex + batchSize > totalBinsCount"
                    @click="nextBatch"
                  >
                    Next Batch <i class="bi bi-chevron-right ms-1"></i>
                  </button>
                </div>

                <div class="d-flex align-items-center gap-1">
                  <button
                    type="button"
                    class="btn btn-outline-secondary btn-sm py-1 px-2"
                    style="font-size: 0.74rem;"
                    @click="setQuickPreset(1, 10)"
                  >
                    1-10
                  </button>
                  <button
                    type="button"
                    class="btn btn-outline-secondary btn-sm py-1 px-2"
                    style="font-size: 0.74rem;"
                    @click="setQuickPreset(11, 10)"
                  >
                    11-20
                  </button>
                  <button
                    type="button"
                    class="btn btn-outline-secondary btn-sm py-1 px-2"
                    style="font-size: 0.74rem;"
                    @click="setQuickPreset(1, totalBinsCount || 50)"
                  >
                    All ({{ totalBinsCount }})
                  </button>
                </div>
              </div>
            </div>

            <!-- Dynamic Range Live Banner -->
            <div class="range-info-banner">
              <i class="bi bi-info-circle-fill text-info me-2"></i>
              <span v-if="totalBinsCount > 0">
                Extracting BINs from <strong class="text-white">#{{ startIndex }}</strong> to
                <strong class="text-white">#{{ rangeEnd }}</strong> of
                <strong class="text-info">{{ totalBinsCount }}</strong> available records.
              </span>
              <span v-else class="text-muted">
                No matching BIN records found with the selected filter criteria.
              </span>
            </div>
          </div>
        </div>
      </div>

      <!-- RIGHT COLUMN: Semicolon Formatted Output & Copy Panel -->
      <div class="col-lg-6">
        <div class="card-panel h-100 d-flex flex-column">
          <!-- Output Header -->
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
              <h6 class="text-white fw-bold mb-0">Formatted Semicolon Output</h6>
              <span class="text-muted small">Ready for pasting into NBR VAT Portal search box</span>
            </div>
          </div>

          <!-- Full Output Textarea -->
          <div class="flex-grow-1 position-relative mb-3 output-area-container">
            <textarea
              :value="formattedOutput"
              readonly
              class="form-control idp-input h-100 font-monospace output-textarea"
              placeholder="Semicolon formatted BINs will appear here automatically..."
            ></textarea>
          </div>

          <!-- Copy Button & Stats Bar -->
          <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 pt-2 border-top border-secondary">
            <div class="text-muted small font-monospace">
              <span>Length: <strong>{{ formattedOutput.length }}</strong> chars</span>
              <span class="mx-2">•</span>
              <span>Items: <strong>{{ selectedBatchBins.length }}</strong></span>
            </div>

            <button
              type="button"
              class="btn btn-sm px-3 py-1 fw-medium d-inline-flex align-items-center gap-1"
              :class="copied ? 'btn-success' : 'btn-primary'"
              :disabled="!formattedOutput"
              @click="copyToClipboard"
            >
              <i class="bi" :class="copied ? 'bi-check2' : 'bi-clipboard'"></i>
              <span>{{ copied ? 'Copied!' : 'Copy' }}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.bin-formatter-page {
  font-family: 'Inter', sans-serif;
  color: #f8f9fa;
}

.card-panel {
  background: #212529;
  border: 1px solid #3b424b;
  border-radius: 10px;
  padding: 1.35rem 1.45rem;
  box-shadow: 0 4px 14px rgba(0, 0, 0, 0.2);
}

/* KPI Chips */
.kpi-chip {
  background: #1a1d21;
  border: 1px solid #323842;
  border-radius: 8px;
  padding: 6px 14px;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}
.kpi-label {
  font-size: 0.7rem;
  color: #adb5bd;
  text-transform: uppercase;
  letter-spacing: 0.3px;
}
.kpi-val {
  font-size: 1.05rem;
  font-weight: 700;
  font-family: monospace;
  line-height: 1.1;
}

/* Mode Switcher */
.mode-switcher-wrap {
  display: flex;
  background: #181b1f;
  border: 1px solid #323842;
  border-radius: 8px;
  padding: 4px;
  gap: 4px;
}
.mode-switch-btn {
  flex: 1;
  background: transparent;
  border: none;
  color: #adb5bd;
  font-size: 0.88rem;
  font-weight: 600;
  padding: 9px 16px;
  border-radius: 6px;
  transition: all 0.2s ease;
  cursor: pointer;
}
.mode-switch-btn:hover {
  color: #ffffff;
}
.mode-switch-btn.active {
  background: #3b8eed;
  color: #ffffff;
  box-shadow: 0 2px 8px rgba(59, 142, 237, 0.3);
}

/* Database Filter Panel */
.db-filter-panel {
  background: rgba(59, 142, 237, 0.05);
  border: 1px solid rgba(59, 142, 237, 0.2);
}

/* Range Panel */
.range-panel {
  background: #181b1f;
  border: 1px solid #323842;
}
.range-info-banner {
  background: rgba(13, 202, 240, 0.08);
  border: 1px solid rgba(13, 202, 240, 0.2);
  border-radius: 6px;
  padding: 10px 14px;
  font-size: 0.82rem;
  color: #adb5bd;
}

/* Inputs */
.idp-input {
  background: #181b1f !important;
  border-color: #3b424b !important;
  color: #f8f9fa !important;
}
.idp-input:focus {
  border-color: #3b8eed !important;
  box-shadow: 0 0 0 0.2rem rgba(59, 142, 237, 0.2) !important;
}

/* Output Area */
.output-area-container {
  min-height: 280px;
}
.output-textarea {
  font-size: 0.92rem;
  line-height: 1.8;
  resize: none;
  background: #16181b !important;
  color: #0dcaf0 !important;
  padding: 18px;
  border-color: #3b424b !important;
  border-radius: 8px;
}
</style>
